./bin2c/bin2c ./bin/0x72_DungeonTilesetII_v1.4.png tiles.h TILES
./bin2c/bin2c ./bin/cursor.png cursor.h CURSOR
./bin2c/bin2c ./bin/DungeonFont.ttf dungeonfont.h FONT
./bin2c/bin2c ./bin/help.png help.h HELP
./bin2c/bin2c ./bin/UI.png UI.h UI
./bin2c/bin2c ./bin/bgm.mp3 bgm.h bgm
./bin2c/bin2c ./bin/victory.mp3 victory.h victory
./bin2c/bin2c ./bin/button.wav button_wav.h BUTTON_WAV
./bin2c/bin2c ./bin/arrow.wav arrow_wav.h ARROW_WAV
./bin2c/bin2c ./bin/damage.wav damage_wav.h DAMAGE_WAV 
./bin2c/bin2c ./bin/death.wav death_wav.h DEATH_WAV
./bin2c/bin2c ./bin/hit.wav hit_wav.h HIT_WAV
